### ISSUE TITLE
submit feedback

### ISSUE THREAD

**Issue by paszin** [paszin/goalden#5]

**Comment by clarkjung** [comment]
localhost:9000/api/users/:uid_from/feedback/:uid_to -> submit feedback

**Comment by clarkjung** [comment]
when frontend integrates this API, close this issue.

**Comment by paszin** [comment]
@clarkjung what is the format for the feedback?
(`var feedback = req.body.feedback;`)
`["thumps_up", ..]` ?

**Comment by clarkjung** [comment]
{
    "feedback": {
        "positive_attitude": 1,
        "high_five": 1
    }
}

"feedback" only includes the ones with the value equals to or above 1. For example, you can use 

{
    "feedback": {
        "positive_attitude": 1,
        "high_five": 1
    }
}

instead of 

{
    "feedback": {
        "positive_attitude": 1,
        "high_five": 1,
        "thumbs_up": 0,
        "positive_attitude": 0
    }
}

(both work though)

Also, since the value is always binary, we can change them boolean.

**Comment by clarkjung** [comment]
Also, please note that since the endpoint is 

router.post('/:uid_from/feedback/:uid_to', auth.isAuthenticated(), controller.submitFeedback);

the "feedback" above only contains the feedback for the user of ":uid_to", which means that you might have to call multiple APIs for each user. If you want to make it such that a user gives feedback for multiple users by clicking on the "submit feedback" button, I can change it accordingly. Let me know.

**Comment by paszin** [comment]
Same thoughts on my side. For now I would just send several post request. Let's keep that in mind, we may change this somehow in the future. 

More important: **We don't store who gave the feedback, which leads to that you can feedback the same person several times.**

**Comment by paszin** [comment]
@clarkjung  I can successfully send feedback (`data = {"smile":1,"excellent_player":1,"high_five":1}`).
But when I call the `users/me`data, feedback is still an empty list.

**Comment by clarkjung** [comment]
@paszin It is working fine on my side. Are you using localhost DB? I am using the Heroku Mongo DB, and it is working fine. 

This is a working example. 

endpoint: localhost:9000/api/users/570b0cbb1a123f980afe9008/feedback/5701ea48bf5e616834cd22ea
body: 
{
    "feedback": {
        "positive_attitude": 1,
        "high_five": 1
    }
}

Can you try this and see if it is working?

**Comment by paszin** [comment]
the difference was in the body: `{
"positive_attitude": 1,
"high_five": 1
}` vs. `{
"feedback": {
"positive_attitude": 1,
"high_five": 1
}
}`

**Comment by clarkjung** [comment]
ok. please use the body format above then :)

**Comment by paszin** [comment]
done, see #11 for follow up
