### ISSUE TITLE
set flag for joined games

### ISSUE THREAD

**Issue by paszin** [paszin/goalden#9]
When I joined the game the api games should have a fag so notify that I am in the game. 

Should be useful to do this in the backend.

**Comment by clarkjung** [comment]
Do you mean, notify in the JSON response?

**Comment by paszin** [comment]
when calling the `games` endpoint I get

upcoming: [{id: ..., 
date: "2016-04-12T02:47:32.682Z", 
estimated_players: 10, 
name: ..., 
**joined: true**
}], 
passed: [{id: ..., 
date: "2016-04-10T02:47:32.682Z", 
estimated_players: 13, 
name: ..., 
**joined: false**
}]

the bold attributes are not yet implemented. 

Should be the same as `me in game.players` (or mentors)

**Comment by clarkjung** [comment]
set flag for joined games done

**Comment by paszin** [comment]
good job, works as expected :)
